security:
  password_hashers:
    App\Entity\User: "auto"
    Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
      algorithm: "auto"
      cost: 15

  providers:
    app_user_provider:
      entity:
        class: App\Entity\User
        property: username

  firewalls:
    login:
      pattern: ^/api/login
      stateless: true
      json_login:
        username_path: username
        password_path: password
        check_path: /api/login
        success_handler: lexik_jwt_authentication.handler.authentication_success
        failure_handler: lexik_jwt_authentication.handler.authentication_failure

    main:
      pattern: ^/api
      stateless: true
      entry_point: jwt
      jwt: ~

  access_control:
    - { path: ^/api/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }

  role_hierarchy:
    ROLE_ADMIN: [ROLE_MANAGE_GENUS, ROLE_ALLOWED_TO_SWITCH]
