vich_uploader:
    db_driver: orm

    metadata:
        type: attribute

    mappings:
    
       products:
           uri_prefix: '%app.path.images%'
           upload_destination: '%kernel.project_dir%/public%app.path.images%'
           namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
           delete_on_update: false
           delete_on_remove: false
